AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  S3 auto-translator - automatically translates objects (up to 5000 characters in size) into
  a user-specified list of languages, written into a 'translations' folder.

Parameters:
  TargetLanguage:
    Type: String
    Default: 'fr'
    Description: (Required) A list of target language codes (separated by spaces)
  InputBucketName:
    Type: String
    Default: 's3-auto-translator'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  InputS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref InputBucketName
  TranslatorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: translatorFunction/
      Handler: app.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Environment:
        Variables:
          targetLanguage: !Ref TargetLanguage
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref InputBucketName
        - Statement:
          - Effect: Allow
            Resource: '*'
            Action:
              - translate:*
              - comprehend:DetectDominantLanguage
              - cloudwatch:GetMetricStatistics
              - cloudwatch:ListMetrics
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref InputS3Bucket
            Events: s3:ObjectCreated:*
            Filter: 
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.txt'            

Outputs:
  TranslatorFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt TranslatorFunction.Arn
  TranslatorFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt TranslatorFunctionRole.Arn
  InputS3Bucket:
    Description: Input S3 bucket
    Value: !Ref InputS3Bucket
